name: Lead Lag CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.11 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Lint
        run: |
          pip install flake8
          flake8 . --count --max-complexity 12 --max-line-length 127 --select=E9,F63,F7,F82 --show-source --statistics
      - name: Install
        run: |
          make install
      - name: Test
        run: |
          make test
